# serverless.yml

service: my-express-application

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1

functions:
  app:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
    environment:
      PORT: 4000
      SUPABASE_URL: sampleurl
      SUPABASE_KEY: samplekey